# Call fusions with `STAR-Fusion` and `FusionInspector` {#ch:fusions}

Here we suggest to ways to detect fusions from RNA-Seq samples which depends on whether one is doing an exploratory or confirmatory analysis for specific recurrent fusions (requiring high sensitivity). The former analysis can be performed with [`STAR-Fusion`](https://github.com/STAR-Fusion/STAR-Fusion/wiki) and the second analysis with [`FusionInspector`](https://github.com/FusionInspector/FusionInspector/wiki) which is now integrated into `STAR-Fusion` as a sub module. `STAR-Fusion` uses the chimeric reads output from the `STAR` aligner to detect fusion trascripts. The [wiki](https://github.com/STAR-Fusion/STAR-Fusion/wiki) page of `STAR-Fusion` describes how to prepare all the necessary files and software requirements to run the fusion callers. These steps are also summarised in the `../functions/star_fusion_prepare.sh` file and they need to be run only once. The wiki pages for both software also provide a detailed information about how to interpret the results. 
